Repository aws/copilot-cli, pull requests merged in 2019-12, with the labels that each got.

#507 Enable per-app integration tests
  internal/pkg/archer/manifest.go
  internal/pkg/cli/pipeline_init.go
  internal/pkg/cli/pipeline_init_test.go
  internal/pkg/cli/pipeline_update.go
  internal/pkg/cli/pipeline_update_test.go
  internal/pkg/deploy/cloudformation/pipeline_integration_test.go
  internal/pkg/deploy/cloudformation/stack/pipeline.go
  internal/pkg/deploy/cloudformation/stack/pipeline_test.go
  internal/pkg/deploy/cloudformation/stack/testdata/rendered_pipeline_cfn_template.yml
  internal/pkg/deploy/cloudformation/stack/testdata/rendered_pipeline_with_no_application_cfn_template.yml
  internal/pkg/deploy/pipeline.go
  internal/pkg/manifest/app_manifest.go
  internal/pkg/manifest/lb_fargate_manifest.go
  internal/pkg/manifest/pipeline.go
  internal/pkg/manifest/pipeline_test.go
  internal/pkg/workspace/workspace_test.go
  templates/cicd/buildspec_integ.yml
  templates/cicd/pipeline.yml
  templates/cicd/pipeline_cfn.yml
Labels: pipeline

#517 Write integration test buildspec to each app's folder
  internal/pkg/cli/pipeline_init.go
  internal/pkg/cli/pipeline_init_test.go
Labels: pipeline

#567 refactor: use sessions as singletons
  internal/pkg/aws/session/session.go
  internal/pkg/cli/app_delete.go
  internal/pkg/cli/app_deploy.go
  internal/pkg/cli/app_init.go
  internal/pkg/cli/app_package.go
  internal/pkg/cli/env_delete.go
  internal/pkg/cli/env_init.go
  internal/pkg/cli/init.go
  internal/pkg/cli/pipeline_update.go
  internal/pkg/cli/project_init.go
  internal/pkg/describe/webapp.go
  internal/pkg/store/secretsmanager/secretsmanager.go
  internal/pkg/store/store.go
Labels: debt

#569 refactor: app deploy cmd satisfies the actionCommand interface
  Makefile
  internal/pkg/cli/app.go
  internal/pkg/cli/app_deploy.go
  internal/pkg/cli/app_deploy_test.go
  internal/pkg/cli/cli.go
  internal/pkg/cli/deploy.go
  internal/pkg/cli/init.go
  internal/pkg/cli/init_test.go
  internal/pkg/cli/mocks/mock_cli.go
  internal/pkg/cli/mocks/mock_projectservice.go
  internal/pkg/describe/mocks/mock_describe.go
Labels: debt

#571 fix: override project name if passed in as a flag
  internal/pkg/cli/app.go
  internal/pkg/cli/app_init.go
  internal/pkg/cli/app_init_test.go
  internal/pkg/cli/app_list.go
  internal/pkg/cli/cli.go
  internal/pkg/cli/env.go
  internal/pkg/cli/flag.go
  internal/pkg/cli/pipeline.go
  internal/pkg/cli/pipeline_init.go
  internal/pkg/cli/pipeline_update.go
Labels: bug
