Repository aws/copilot-cli, pull requests merged in 2020-05, with the labels that each got.

#892 fix(env): initialize profile sessions before checking for dns delegation
  internal/pkg/cli/env_init.go
Labels: area/env, type/bug

#901 fix(cli): "app status" mentions status instead of logs
  internal/pkg/cli/app_status.go
  internal/pkg/cli/app_status_test.go
Labels: type/bug

#902 fix(pipeline): buildspec works with dockerfiles in subdirs
  templates/cicd/buildspec.yml
Labels: type/bug

#917 test(describe): fix flaky "app status" tests due to passing time
  internal/pkg/cli/app_status_test.go
  internal/pkg/describe/status.go
  internal/pkg/describe/status_test.go
Labels: type/test

#942 test(e2e): fix multi svc test to expect the proper count
  e2e/multi-svc-app/multi_svc_app_test.go
Labels: type/test

#947 chore(deps): upgrade and tidy dependencies
  go.mod
  go.sum
Labels: dependencies

#953 style: update root help menu for more descriptive commands
  cmd/copilot/description.go
  cmd/copilot/description_windows.go
  cmd/copilot/main.go
  cmd/copilot/template/macro.go
  cmd/copilot/template/template.go
  cmd/copilot/template/template_windows.go
  internal/pkg/cli/app.go
  internal/pkg/cli/env.go
  internal/pkg/cli/group/group.go
  internal/pkg/cli/group/group_windows.go
  internal/pkg/cli/init.go
  internal/pkg/cli/pipeline.go
  internal/pkg/cli/svc.go
  internal/pkg/cli/wiki.go
Labels: type/enhancement

#956 fix: add build tag to description.go to make it work on windows
  cmd/copilot/description.go
Labels: platform/windows, type/bug

#957 fix: cicd buildspec works with copilot binary
  templates/cicd/buildspec.yml
Labels: area/pipeline, type/bug

#907 feat(cli): Add data structures for storage init ask() and validate() calls
  cmd/copilot/main.go
  cmd/copilot/template/template.go
  internal/pkg/cli/flag.go
  internal/pkg/cli/group/group.go
  internal/pkg/cli/group/group_windows.go
  internal/pkg/cli/storage.go
  internal/pkg/cli/storage_init.go
  internal/pkg/cli/storage_init_test.go
  internal/pkg/cli/validate.go
  internal/pkg/cli/validate_test.go
Labels: area/addon, type/feature

#940 feat: pipeline show execute
  Makefile
  internal/pkg/aws/codepipeline/codepipeline.go
  internal/pkg/aws/codepipeline/codepipeline_test.go
  internal/pkg/cli/flag.go
  internal/pkg/cli/pipeline_show.go
  internal/pkg/cli/pipeline_show_test.go
  internal/pkg/describe/backend_service.go
  internal/pkg/describe/describe.go
  internal/pkg/describe/lb_web_service.go
  internal/pkg/describe/mocks/mock_describe.go
  internal/pkg/describe/mocks/mock_lb_web_service.go
  internal/pkg/describe/mocks/mock_pipeline.go
  internal/pkg/describe/pipeline.go
  internal/pkg/describe/pipeline_test.go
  internal/pkg/describe/service.go
Labels: area/pipeline

#965 fix: has secrets was returning true when there were 0 secrets
  internal/pkg/template/service.go
  internal/pkg/template/service_test.go
Labels: type/bug

#974 style: reduce feedback noise for logs and prompts
  internal/pkg/cli/app_init.go
  internal/pkg/cli/app_init_test.go
  internal/pkg/cli/env_init.go
  internal/pkg/cli/env_init_test.go
  internal/pkg/cli/init.go
  internal/pkg/cli/init_test.go
  internal/pkg/cli/mocks/mock_prompter.go
  internal/pkg/cli/prompter.go
  internal/pkg/cli/selector/selector.go
  internal/pkg/cli/svc_deploy.go
  internal/pkg/cli/svc_init.go
  internal/pkg/cli/svc_init_test.go
  internal/pkg/term/color/color.go
  internal/pkg/term/prompt/prompt.go
  internal/pkg/term/prompt/prompt_test.go
Labels: type/enhancement

#976 style(cli): collapse log message after user selects new app name
  internal/pkg/cli/app_init.go
Labels: type/enhancement
