Repository aws/copilot-cli, pull requests merged in 2020-07, with the labels that each got.

#1127 fix: do not remove svc from app when running `svc delete --env`
  internal/pkg/cli/svc_delete.go
  internal/pkg/cli/svc_delete_test.go
Labels: type/bug

#1175 docs(README): include the latest release version as a badge
  README.md
Labels: type/documentation

#1187 build(site): update dependencies to mitigate CVE-2020-8203
  site/README.md
  site/package-lock.json
  site/package.json
Labels: dependencies
